### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by tchaton** [lixiang-ucas/DANCE-NET#1]
Hey @lixiang-ucas , 

I was wondering when the code will be released and is it in Pytorch or Tensorflow ?

Best,
Thomas Chaton

**Comment by lixiang-ucas** [comment]
Hi, our paper is still under review, we will release the code once it got accepted. Our code was written in Tensorflow. Thanks.

**Comment by shnhrtkyk** [comment]
Accepted? Congratulations ! 👍
