### ISSUE TITLE
Looking forward to

### ISSUE THREAD

**Issue by cystal-lili** [lixiang-ucas/DANCE-NET#6]
Looking forward to the open source of the code, has it been deleted or has not been uploaded?

**Comment by lixiang-ucas** [comment]
uploaded now.

**Comment by cystal-lili** [comment]
OK&nbsp; thanks&nbsp; fighting&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang-ucas/DANCE-NET"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午5:48
收件人:&nbsp;"lixiang-ucas/DANCE-NET"<DANCE-NET@noreply.github.com&gt;;
抄送:&nbsp;"或许"<1922797937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang-ucas/DANCE-NET] Looking forward to (#6)





 
uploaded now.

**Comment by cystal-lili** [comment]
Hello, does this code need to be recompiled when running on windows? thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang-ucas/DANCE-NET"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午5:48
收件人:&nbsp;"lixiang-ucas/DANCE-NET"<DANCE-NET@noreply.github.com&gt;;
抄送:&nbsp;"或许"<1922797937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang-ucas/DANCE-NET] Looking forward to (#6)





 
uploaded now.

**Comment by lixiang-ucas** [comment]
Never tried. You'd better abandon windows if you want to use tensorflow.

**Comment by cystal-lili** [comment]
I should use the Ubantu system for data processing will be better, thank you for your reply I am trying
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang-ucas/DANCE-NET"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 晚上8:29
收件人:&nbsp;"lixiang-ucas/DANCE-NET"<DANCE-NET@noreply.github.com&gt;;
抄送:&nbsp;"或许"<1922797937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang-ucas/DANCE-NET] Looking forward to (#6)





 
Never tried. You'd better abandon windows if you want to use tensorflow.

**Comment by cystal-lili** [comment]
Hello, the so file has been configured. There are several questions about the code 1. Is the data downloaded by yourself? I think there is data/train_1581.pickle, but I don’t understand it. Is the data set I downloaded in this format? 2. Is the training code and test code in one .py? 3. The difference between train_feature_context.py and train_feature_context_dfc_n128.py Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang-ucas/DANCE-NET"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 晚上8:29
收件人:&nbsp;"lixiang-ucas/DANCE-NET"<DANCE-NET@noreply.github.com&gt;;
抄送:&nbsp;"或许"<1922797937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang-ucas/DANCE-NET] Looking forward to (#6)





 
Never tried. You'd better abandon windows if you want to use tensorflow.

**Comment by cystal-lili** [comment]
Hello, regarding the question I asked you yesterday, I read the paper and found out the difference between the two codes of trainli, but the data set is still unclear. Can I share the data set of ISPRS? Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang-ucas/DANCE-NET"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 晚上8:29
收件人:&nbsp;"lixiang-ucas/DANCE-NET"<DANCE-NET@noreply.github.com&gt;;
抄送:&nbsp;"或许"<1922797937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang-ucas/DANCE-NET] Looking forward to (#6)





 
Never tried. You'd better abandon windows if you want to use tensorflow.
